spring:
  datasource:
    url: jdbc:mysql://3.38.21.160:3306/musicat_audio
    username: scott
    password: Tiger_1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernat:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace